name: ARM64 Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install ARM64 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwxgtk3.2-dev

      - name: Build
        run: |
          cd bbn-MotionCal && mkdir build && cd build
          cmake ..
          make -j 4
          
